version: '3.8'

services:
  backend:
    build: ./backend
    image: backend
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    networks:
      - chatbot

networks:
  chatbot:
    driver: bridge
